name: deploy backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t backend-image .

      - name: Publish image to Docker Hub
        run: docker push backend-image:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull backend-image:latest

      - name: Stop and remove existing container
        run: |
          docker stop backend-container || true
          docker rm backend-container || true

      - name: Run new container
        run: docker run -d --name backend-container -p 3000:3000 -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} -e MONGO_URI=${{ secrets.MONGO_URI }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} backend-image:latest 